# DATA SPILT & SIMPLE MATCH
## Xilin Tian

In [1]:
import pandas as pd
import numpy as np

In [2]:
resume = pd.read_excel ('resume_add_skills.xlsx')
resume

ID  Category                                             Resume  \
0            1        HR  b'John H. Smith, P.H.R.\n800-991-5187 | PO Box...   
1            2        HR  b'Name Surname\nAddress\nMobile No/Email\nPERS...   
2            3        HR  b'Anthony Brown\nHR Assistant\nAREAS OF EXPERT...   
3            4        HR  b'www.downloadmela.com\nSatheesh\nEMAIL ID:\nC...   
4            5        HR  b"HUMAN RESOURCES DIRECTOR\n\xef\x82\xb7Expert...   
...        ...       ...                                                ...   
3672  99416532  AVIATION           RANK: SGT/E-5 NON- COMMISSIONED OFFIC...   
3673  24589765  AVIATION           GOVERNMENT RELATIONS, COMMUNICATIONS ...   
3674  31605080  AVIATION           GEEK SQUAD AGENT         Professional...   
3675  21190805  AVIATION           PROGRAM DIRECTOR / OFFICE MANAGER    ...   
3676  37473139  AVIATION           STOREKEEPER II       Professional Sum...   

      branding  collateral  competitive analysis  content  customer journeys  \
0            0           0                     0        0                  0   
1            0           0                     0        0                  0   
2            0           0                     0        0                  0   
3            0           0                     0        0                  0   
4            0           0                     0        0                  0   
...        ...         ...                   ...      ...                ...   
3672         0           0                     0        0                  0   
3673         0           0                     0        0                  0   
3674         0           0                     0        0                  0   
3675         0           0                     0        0                  0   
3676         0           0                     0        0                  0   

      data analytics  ecommerce  ...  inbound marketing  influencer marketing  \
0                  0          0  ...                  0                     0   
1                  0          0  ...                  0                     0   
2                  0          0  ...                  0                     0   
3                  0          0  ...                  0                     0   
4                  0          0  ...                  0                     0   
...              ...        ...  ...                ...                   ...   
3672               0          0  ...                  0                     0   
3673               0          0  ...                  0                     0   
3674               0          0  ...                  0                     0   
3675               0          0  ...                  0                     0   
3676               0          0  ...                  0                     0   

      new market development  paid media and advertising  positioning  SEO  \
0                          0                           0            0    0   
1                          0                           0            0    0   
2                          0                           0            0    0   
3                          0                           0            0    0   
4                          0                           0            0    0   
...                      ...                         ...          ...  ...   
3672                       0                           0            0    0   
3673                       0                           0            0    0   
3674                       0                           0            0    0   
3675                       0                           0            0    0   
3676                       0                           0            0    0   

      social media  webinars  website development  WordPress  
0                0         1                    0          0  
1                0         0                    0          0  
2  

pick random number and find the best 10 macth
weibste https://en.wikipedia.org/wiki/S%C3%B8rensen%E2%80%93Dice_coefficient

 $$DSC={\frac {2TP}{2TP+FP+FN}}$$

In [3]:
""" Sørensen–Dice coefficient (Dice similarity coefficient) """
def dice_coefficient(a, b, x, y):
    TP = 0
    FP_FN = 0
    if x == y:
        TP += 1
    for i in range(len(a)):
        if a[i] == 0:
            FP_FN += 1
        if a[i] == 1:
            if b[i] == 0:
                FP_FN += 1
            if b[i] == 1:
                TP += 1
    score = 2*TP/(2*TP + FP_FN)
    return score

In [4]:
X = resume.drop(columns = ['ID','Category','Resume']).to_numpy()
y = resume['Category'] # Label

In [5]:
import random
random_resume = random.randrange(0, 3677, 1) # Randomly choose a resume
print(random_resume)

312


In [6]:
DSC_Score = []

for i in range(3677):
    score = dice_coefficient(X[random_resume,], X[i,], y[random_resume], y[i])
    string = "{} -- Resume {} to {}".format(score, i, random_resume)
    DSC_Score.append(string)
    

DSC_Score.sort(reverse=True) # sort the list in descending list
print('The firt tenth matches are:', DSC_Score[:10])

The firt tenth matches are: ['0.09090909090909091 -- Resume 371 to 312', '0.09090909090909091 -- Resume 370 to 312', '0.09090909090909091 -- Resume 369 to 312', '0.09090909090909091 -- Resume 368 to 312', '0.09090909090909091 -- Resume 367 to 312', '0.09090909090909091 -- Resume 366 to 312', '0.09090909090909091 -- Resume 365 to 312', '0.09090909090909091 -- Resume 364 to 312', '0.09090909090909091 -- Resume 363 to 312', '0.09090909090909091 -- Resume 362 to 312']


________________
Create fake test data, then apply to the fuction to find the best matches with the resume_add_skills dataset.

In [7]:
test_data = np.array([[1,1,1,1,1,0,0,0,0,0,1,1,1,1,1,0,0,0,0,0], [0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,1,1,1,1,1], [0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1], [1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0]])
print(test_data)

[[1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0]
 [0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]]


In [8]:
DSC_Score_test = []

for i in range(3677):
    score = dice_coefficient(test_data[0,], X[i,], 'Banking', y[i]) # ‘Banking’ is randomly chosen, same as follows.
    string = "{} -- Resume {}".format(score, i)
    DSC_Score_test.append(string)
    

DSC_Score_test.sort(reverse=True) # sort the list in descending list
print('The firt tenth matches for the first test data are:', DSC_Score_test[:10])

DSC_Score_test = []

for i in range(3677):
    score = dice_coefficient(test_data[1,], X[i,], 'Accountant', y[i])
    string = "{} -- Resume {}".format(score, i)
    DSC_Score_test.append(string)
    

DSC_Score_test.sort(reverse=True) # sort the list in descending list
print('The firt tenth matches for the second test data are:', DSC_Score_test[:10])

DSC_Score_test = []

for i in range(3677):
    score = dice_coefficient(test_data[2,], X[i,], 'Education', y[i])
    string = "{} -- Resume {}".format(score, i)
    DSC_Score_test.append(string)
    

DSC_Score_test.sort(reverse=True) # sort the list in descending list
print('The firt tenth matches for the third test data are:', DSC_Score_test[:10])

DSC_Score_test = []

for i in range(3677):
    score = dice_coefficient(test_data[3,], X[i,], 'HR', y[i])
    string = "{} -- Resume {}".format(score, i)
    DSC_Score_test.append(string)
    

DSC_Score_test.sort(reverse=True) # sort the list in descending list
print('The firt tenth matches for the forth test data are:', DSC_Score_test[:10])

The firt tenth matches for the first test data are: ['0.4 -- Resume 2866', '0.3333333333333333 -- Resume 3291', '0.3333333333333333 -- Resume 2521', '0.3333333333333333 -- Resume 2432', '0.3333333333333333 -- Resume 1370', '0.2608695652173913 -- Resume 719', '0.2608695652173913 -- Resume 704', '0.2608695652173913 -- Resume 671', '0.2608695652173913 -- Resume 651', '0.2608695652173913 -- Resume 49']
The firt tenth matches for the second test data are: ['0.46153846153846156 -- Resume 2432', '0.46153846153846156 -- Resume 2215', '0.4 -- Resume 3558', '0.4 -- Resume 2526', '0.4 -- Resume 1793', '0.3333333333333333 -- Resume 719', '0.3333333333333333 -- Resume 692', '0.3333333333333333 -- Resume 3336', '0.3333333333333333 -- Resume 3313', '0.3333333333333333 -- Resume 3289']
The firt tenth matches for the third test data are: ['0.46153846153846156 -- Resume 1793', '0.4 -- Resume 3558', '0.4 -- Resume 2511', '0.4 -- Resume 2432', '0.4 -- Resume 2215', '0.3333333333333333 -- Resume 692', '0.3

In [9]:
print(test_data[0,], 'Banking') # Compare the test data with the first 2 best matches resume
print(X[2866,], y[2866])
print(X[3291,], y[3291])

[1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0] Banking
[1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0] APPAREL
[1 1 0 1 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0] PUBLIC-RELATIONS


____

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1) # Set Train and Test dataset
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.25, random_state=1) # Set Validation data set, 0.25 x 0.8 = 0.2

In [11]:
nums_of_category = y.drop_duplicates().shape # numbers of different category, k = 47
print(nums_of_category)

(47,)


In [ ]:
import gensim
from gensim.models import Word2Vec, KeyedVectors
import multiprocessing